### ISSUE TITLE
2425-W-002 Google Smart Chips

### ISSUE THREAD

**Issue by saumier** [culturecreates/nebula#22]
Reference: https://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit

Prototype a Google Sheet to upload simple events to Artsdata and using Google smart chips to preview URIs directly in the Google sheet. Artsdata K-number URIs can be entered directly into the spreadsheet for places, performers, organizers, event types, etc. instead of having to enter the data about each manually.

The idea is to use smart chips so the user could roll over cells to see the full details from Artsdata. 

We want to demo the user experience of entering events into the spreadsheet and uploading to Artsdata.

Here is a Google sheet but without the smart chip (not built yet). But if you roll over the Main Webpage URL cell you can get an idea of the smart chip potential.
https://docs.google.com/spreadsheets/d/1MY-6ckSH34Olw3hwKrJDSg7kbYlGinmDr5aRP6cvp2o/edit?usp=sharing

## Fields for prototype:
- title
- event type (Artsdata Event Type URI)
- description
- startDate
- startTime
-  location (URI)
- performer (URI)
- organizer (URI)
- image (URL)

This proptype would develop a smart chip feature of Google sheets:
1. [preview-links](https://developers.google.com/apps-script/add-ons/editors/gsao/preview-links) - to make a card appear when you roll over the K-number to display the name and details from Artsdata.

# Use Case
This is the user flow for the MVP.
1. open a copy of a Google sheet with the standard column headers and the "Artsdata smart chip" extension already added
2. Enter your event data
3. Review your work (roll over K-numbers to see the full details in the smart chip)
4. Open another browser window and go to Artsdata.ca
5. Login using your GitHub account
6. Select load Google spreadsheet from the menu (new for Gregory to add to Nebula)
7. In the form enter the url of the spreadsheet and click the load button.
8. Nebula triggers a Github workflow that is configured with standard column headings using OntoRefine to download the spreadsheet url (passed as parameter), convert to RDF and upload data via the Artsdata Databus.

## Timeline
The timeline s to have an MVP by mid June, so that Dessa (CAPACOA) can recruit potential testers at the ArtsReach conference, on June 25.

**Bonus**:  After the minimal use flow is working, we can create a smart chip for reconciliation. For example in the performer cell you would start by typing the name of the performer and then selecting a K-number match from the popup list in the smart chip.

**Bonus**: The spreadsheet should display the Artsdata URI for events (read only) after the spreadsheet is uploaded.  The script would automatically add the event URIs.

**Comment by saumier** [comment]
@dev-aravind I changed the Artsdata response when dereferencing to not expand the sameAs. So now there is less data and both entities look more similar. [K5-381](http://kg.artsdata.ca/en/entity.jsonld?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK5-381), [K16-294](http://kg.artsdata.ca/en/entity.jsonld?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK16-294)

**Comment by dev-aravind** [comment]
@saumier I've added a [workflow](https://github.com/culturecreates/artsdata-google-workspace-smart-chip/blob/main/.github/workflows/push-google-sheets-to-artsdata.yml) to push events to artsdata using a [google sheet](https://docs.google.com/spreadsheets/d/1fPcWbdSL-gcLmeGWVCID9TjBq5fGk4vG4HG2E7kSAb0/edit#gid=0). Please check the [event](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Event%20entities%20in%20google-smart-chip%20%2811%20triples%29&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-google-workspace-smart-chip/google-smart-chip) in nebula and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind I took a look. Great to see the spreadsheet imported to Artsdata. I will spend some time to try to suggest ways to shorten the workflow because I think there are several steps that may not be needed. For example there should be a way for OntoRefile to load the url of the spreadsheet directly without having to download it first, and maybe a way to connect a drive to the ontotext docker so you don't have to download the mapping file. But those will be optimizations. If we stay focused on getting the main user flow working, then you should advance the smart chip extension and I will advance adding a form to Nebula to allow a person to enter a url for a spreadsheet and an artifact name so we can trigger the workflow with an http action and pass the spreadsheet url and artifact as parameters.

**Comment by saumier** [comment]
@dev-aravind I added the docker-compose and shell script. So you should be able to run the script to open Ontorefine with the configurations for RDF mapping loaded. 

I also rename the folder data to ontorefine when configuring shell script.

**Comment by saumier** [comment]
Can you check why the email is sent to 3rd party when using this extension?

![Image](https://github.com/culturecreates/nebula/assets/419491/9b61f080-8d5e-4cfc-8137-b81d407b8ac0)

**Comment by saumier** [comment]
@dev-aravind Can you also find out how to add info about the add-on info box. 

![Image](https://github.com/culturecreates/nebula/assets/419491/13e74fb7-abc1-4404-a5a2-4fc10e5f5971)

**Comment by dev-aravind** [comment]
@saumier 
The reason why the email is needed is because our script is actually called as an API by google in it's current state, which requires authorization. The url, the link of the app script project and the user details are sent as payload by the API. Once we can deploy and publish it, there will be an authorization pop-up mentioned details about our extension, what it does and what permissions it needs. 

The basic add on information can be added using the manifest file. I'll update that and the additional details to be displayed for the entities tommorow.

**Comment by dev-aravind** [comment]
@saumier The add-on cannot be made available to anybody who has access to the sheet in it's current state, but the custom menus can be mapped to the onOpen function, so any user opening the sheet with editor access will see the menu (look at the custom menu [here](https://docs.google.com/spreadsheets/d/1fPcWbdSL-gcLmeGWVCID9TjBq5fGk4vG4HG2E7kSAb0/edit#gid=0) without installing the apps script).

**Comment by saumier** [comment]
@dev-aravind when I try your sheet [here](https://docs.google.com/spreadsheets/d/1fPcWbdSL-gcLmeGWVCID9TjBq5fGk4vG4HG2E7kSAb0/edit#gid=0) the smart chip is working with https as well as the menu. I think this is related to the test environment being restricted to within an organization. Can you continue to find a way to enable the smart chip to work for other users not in Culture creates? Can we publish it to move into out of the test deployment area? How long will it take to publish? The real question is how can be get this into the hands of a user that we know called Dessa so she can make a demo to her colleagues. Can we invite her to a spreadsheet with the app script published somewhere?

**Comment by saumier** [comment]
Demo video made and sent to CAPACOA
